### ISSUE TITLE
Intro, History2 내용 중복

### ISSUE THREAD

**Issue by hd132506** [Lee-Null/opensource#10]
Q. 오픈 소스의 저작권은 어떻게 설정되어있나요?

A. 오픈 소스 소프트웨어는 겉보기엔 저작권이 소멸된 저작물로 보일 수 있지만 절대 아니에요. 만약 저작권이 없었다면 누군가가 그것을 약간 수정한 뒤에 독점할게 뻔하죠. 이를 막기 위해 ‘카피레프트’라는 개념이 생겼어요. 이 소프트웨어의 저작권이 보호받고 저작자들은 복사본의 재배포를 허용하고, 수정하거나 무언가를 추가할 수 있는 권한을 주지만, 라이선스의 조항을 따라야 한다는 것 말이죠. 여기서 따라야 하는 라이선스의 조항에 대해 얘기해 보자면, 공통적 준수사항과 선택적 준수사항으로 나뉘어요.

-----------

같은 해인 1985년에 리처드 스톨만은 자유 소프트웨어를 규정함에 있어서 자유의 범위에 대해 고민하였어요. 자유의 범위를 너무나도 넓히면 공공 도메인(public domain)으로 공개된 소프트웨어를 손쉽게 독점 소프트웨어로 변형시킬 수 있었어요. 돕 홉킨스라는 사람이 보낸 편지에서 나오는 "카피레프트"라는 이름을 사용하여 카피레프트라는 방식의 조항을 자유 소프트웨어에 적용하기로 하였어요. 이는 카피레프트 라이선스로 배포된 소프트웨어를 수정해서 배포할 때에도 똑같은 라이선스가 적용된다는 것이에요. 대부분의 GNU 소프트웨어에는 카피레프트를 실제로 구현한 라이선스 기준인 GPL(GNU General Public Lisence)이 적용되어 배포되었어요.

카피레프트에 관한 내용이 중복돼서 이부분 조절해야 할 것 같아

**Comment by nullist0** [comment]
어떻게 해결하는게 좋을까요

**Comment by hd132506** [comment]
같은 해에 리처드 스톨만은 카피레프트의 조항을 자유 소프트웨어에 적용하기로 하였어요. 이렇게 하면 카피레프트 라이선스로 배포된 소프트웨어를 수정해도 라이선스 조항에 따라 독점할 수 없어요. 대부분의 GNU 소프트웨어는 리처드 스톨만이 만든 라이선스로 배포되었어요. 
---
1. 이전부분이랑 중복된 부분 제거
2. GPL도 2-3에서 나오니까 생략
3. 리처드 스톨만이 만든 GPL(GNU General Public Lisence)라이선스로 배포되었어요. 라고 하려 했는데
어차피 뒤에서 다룰 내용이고 없는게 더 깔끔해 보여서 뺐어
---
대략 이정도로..

**Comment by nullist0** [comment]
저렇게 2_2 History 수정하면 될것같다는 이야기야??

**Comment by hd132506** [comment]
응 저 문단 부분

**Comment by nullist0** [comment]
수정 요청과 같이 수정하였습니다.
